Second update
Hennessy811/maraphon_sprint1_todo pull request #5
Opened 2021-03-31 18:41 UTC by Stypticm

2021-03-31 18:41 UTC, ghost commented
<img src="https://www.deepcode.ai/icons/green_check.svg" width= "50px" align= "left"/> Congratulations :tada:. DeepCode [analyzed](https://www.deepcode.ai/app/gh/Hennessy811/maraphon_sprint1_todo/2dd4f703bb936efce4ce82fb361ecc43c8e2c022/Hennessy811/maraphon_sprint1_todo/e396e9f59822f97fecfbbf45d561705f2ccf7dd1/pr/_/%2F/code/?utm_source=gh_review&c=0&w=0&i=0&) your code in 6.004 seconds and we found no issues. Enjoy a moment of no bugs :sunny:.

#### 👉 View analysis in [**DeepCode’s Dashboard**](https://www.deepcode.ai/app/gh/Hennessy811/maraphon_sprint1_todo/2dd4f703bb936efce4ce82fb361ecc43c8e2c022/Hennessy811/maraphon_sprint1_todo/e396e9f59822f97fecfbbf45d561705f2ccf7dd1/pr/_/%2F/code/?utm_source=gh_review&c=0&w=0&i=0&) | [_Configure the bot_](https://www.deepcode.ai/app/gh/?ownerconfig=Hennessy811)

2021-04-01 08:55 UTC, Hennessy811 requested changes

2021-04-01 08:55 UTC, Hennessy811 commented on src/store/features/todos.js
> +        axios
такие штуки нужно делать не в редьюсерах, а как async action. В примере про counter там есть asyncIncrease (или что-то типо того, пример с таймаутом)
в редьюсерах код всегда синхронный

2021-04-01 08:55 UTC, Hennessy811 commented on src/store/features/todos.js
> +    add: (state, items) => {
второй аргумент в редьюсере всегда традиционно называется `action`. У него есть `type` и `payload`. Вот `action.payload` можно назвать `items`.

2021-04-01 08:55 UTC, Hennessy811 commented on src/store/features/todos.js
> +    remove:  (state, todo) => {
```suggestion
    remove:  (state, action) => {
```

2021-04-01 08:55 UTC, Hennessy811 commented on src/store/features/todos.js
> +        const deleteItem = todo.payload.todo
для удаления элемента из массива можно взять 
`state.value = state.value.filter(item => item === action.payload.todo);`

но тут удаление/добавление/изменение должно использовать бекенд и на фронте особо и незачем делать эту обработку

2021-04-01 08:55 UTC, Hennessy811 commented on src/store/features/todos.js
> +    store: (state, items) => {
`store` - это хранилище. нужно более четкое имя, `saveTodos`, к примеру

2021-04-01 08:55 UTC, Hennessy811 commented on src/store/features/todos.js
> +      data.map(item => state.value.push(item.title))
1. это костыль, `data.map` и так возвращает массив, зачем делать `push` внутри?

2. хранить только title плохо, теряются данные (так ты не можешь проверить, какой именно элемент был удален, если у тебя их два с одним именем (но другие свойства могли отличаться), например)

2021-04-01 08:55 UTC, Hennessy811 commented on src/store/features/todos.js
> +      data.map(item => state.value.push(item.title))
надо хранить все полученные данные короче

2021-04-01 08:55 UTC, Hennessy811 commented on src/store/features/todos.js
> +
получение данных тоже должно быть здесь, а не в компоненте

2021-04-01 08:55 UTC, Hennessy811 commented on src/App.js
> +		(async () => {
этот код можно перенести в редьюсер и отюда только вызвать

2021-04-01 08:55 UTC, Hennessy811 commented on src/App.js
> +			const response = await axios.get('http://167.172.176.146/todos');
хорошо бы завести глобальную переменную с IP, чтобы в случае изменений не искать по всему коду
```suggestion
// и где-то отдельно этот BASE_URL = 'http://167.172.176.146';
			const response = await axios.get(`${BASE_URL}/todos`);
```

2021-04-01 08:55 UTC, Hennessy811 commented on src/App.js
> +		let attr = document.getElementById('checkbox' + e.target.id);
нет, работать с DOM напрямую из реакта крайне нежелательно. для индикации выполнения можно придумать что-то другое (иконку добавить, цвет изменить, сделать эелемент disabled)

2021-04-01 08:55 UTC, Hennessy811 commented on package.json
> +    "express": "^4.17.1",
зачем здесь express?

2021-04-01 08:55 UTC, Hennessy811 commented on src/App.js
> +								<ListItem key={index}>
при маппинге элементов нужен атрибут `key` с уникальным id.

2021-04-05 14:23 UTC, merged